n = input('Digite algo : ')
print('O tipo primitivo do valor digitado é {} \n'.format(type(n)))
print('O valor digitado é alfanumérico.. : ', n.isalnum())
print('O valor digitado é numérico...... : ', n.isnumeric())
print('O valor digitado é uma letra..... : ', n.isalpha())
print('O valor digitado é um número real : ', n.isdecimal())
print('O valor digitado é minúsculo..... : ', n.islower())
print('O valor digitado é maiúsculo..... : ', n.isupper())
print('O valor digitado é um espaço..... : ', n.isspace())
